In [4]:
import numpy as np

In [5]:
array1 = np.array([2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31])

In [7]:
array1

array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31])

In [8]:
type(array1)

numpy.ndarray

In [9]:
array1.shape

(11,)

In [12]:
array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [13]:
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
type(array2)

numpy.ndarray

In [15]:
array2.shape

(3, 4)

In [19]:
array1.size

11

In [18]:
array2.size

12

In [20]:
array3 = np.full(5,10)

In [21]:
array3

array([10, 10, 10, 10, 10])

In [22]:
array4 = np.zeros(6, dtype=int)

In [23]:
array4

array([0, 0, 0, 0, 0, 0])

In [24]:
array5 = np.ones(4, dtype=int)

In [25]:
array5

array([1, 1, 1, 1])

In [26]:
array6 = np.random.random(4)

In [27]:
array6

array([0.77883928, 0.06058475, 0.3344229 , 0.52977393])

In [29]:
array7 = np.arange(6)

In [30]:
array7

array([0, 1, 2, 3, 4, 5])

In [31]:
array8 = np.arange(4,10)

In [32]:
array8

array([4, 5, 6, 7, 8, 9])

In [35]:
array9 = np.arange(2,10,3)

In [37]:
import numpy as np

array1 = np.array([2,3,5,7,11,13,17,19,23,29,31])
array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array1.shape
array2.size
array3 = np.full(5,10)
array4 = np.zeros(4, dtype=int)
array5 = np.ones(5, dtype=int)
array6 = np.random.random(7)
array7 = np.arange(5)
array8 = np.arange(3,10)
array9 = np.arange(2,15,3)

In [38]:
array1 = np.array([2,3,5,7,11,13,17,19,23,29,31])

In [39]:
array1[0] #인덱싱(indexing)

2

In [40]:
array1[-1]

31

In [41]:
array1[[1, 3, 4]]

array([ 3,  7, 11])

In [43]:
array2 = np.array([2, 1, 3])

In [44]:
array1[array2]

array([5, 3, 7])

In [45]:
array1[2:7]

array([ 5,  7, 11, 13, 17])

In [47]:
array1[:7]

array([ 2,  3,  5,  7, 11, 13, 17])

In [48]:
array1[2:]

array([ 5,  7, 11, 13, 17, 19, 23, 29, 31])

In [50]:
array1[2:11:2]

array([ 5, 11, 17, 23, 31])

In [51]:
array1 = np.arange(10)
array2 = np.arange(10, 20)

In [52]:
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
array1 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [54]:
array1 + array2

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [55]:
array1 > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [56]:
array1%2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [57]:
booleans = np.array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [58]:
np.where(booleans)

(array([0, 2, 4, 6, 8]),)

In [64]:
filter = np.where(array1 > 4)
filter

(array([5, 6, 7, 8, 9]),)

In [65]:
array1[filter]

array([5, 6, 7, 8, 9])

In [66]:
array1 = np.array([14, 6, 13, 21, 23, 31, 9, 5])

In [68]:
print(array1.max(), array1.min(), array1.mean(), array1.median)

31 5 15.25


In [1]:
#pandas 불러오기
import pandas as pd

In [2]:
two_dimensional_list = [['Hyuna', 20, 160], ['Maria', 46, 158], ['Taeguen', 50, 172]]

In [4]:
my_df = pd.DataFrame(two_dimensional_list)
my_df

0   1    2
0    Hyuna  20  160
1    Maria  46  158
2  Taeguen  50  172

In [5]:
type(my_df)

pandas.core.frame.DataFrame

In [8]:
#column, row이름 짓기
my_df = pd.DataFrame(two_dimensional_list, columns=['Name', 'Age', 'Height'], index=['A','B','C'])
my_df

Name  Age  Height
A    Hyuna   20     160
B    Maria   46     158
C  Taeguen   50     172

In [9]:
my_df.columns

Index(['Name', 'Age', 'Height'], dtype='object')

In [10]:
my_df.index

Index(['A', 'B', 'C'], dtype='object')

In [11]:
my_df.dtypes

Name      object
Age        int64
Height     int64
dtype: object

In [15]:
dimensional_list=[['Taylor Swift','December 13, 1989','Singer-songwriter'],
['Aaron Sorkin','June 9, 1961','Screenwriter'],
['Harry Potter','July 31, 1980','Wizard'],
['Ji-Sung Park','February 25, 1981','Footballer']]

In [17]:
star = pd.DataFrame(dimensional_list, columns=['Name','Birthday','Occupation'])
star

Name           Birthday         Occupation
0  Taylor Swift  December 13, 1989  Singer-songwriter
1  Aaron Sorkin       June 9, 1961       Screenwriter
2  Harry Potter      July 31, 1980             Wizard
3  Ji-Sung Park  February 25, 1981         Footballer

In [19]:
star.dtypes

Name          object
Birthday      object
Occupation    object
dtype: object

In [23]:
iphone_df = pd.read_csv('data/iphone.csv', index_col=0)

In [24]:
iphone_df

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [22]:
type(iphone_df)

pandas.core.frame.DataFrame

In [26]:
baby_name_df = pd.read_csv('data/popular_baby_names.csv')

In [27]:
baby_name_df

Year of Birth  Gender                   Ethnicity Child's First Name  \
0               2016  FEMALE  ASIAN AND PACIFIC ISLANDER             Olivia   
1               2016  FEMALE  ASIAN AND PACIFIC ISLANDER              Chloe   
2               2016  FEMALE  ASIAN AND PACIFIC ISLANDER             Sophia   
3               2016  FEMALE  ASIAN AND PACIFIC ISLANDER              Emily   
4               2016  FEMALE  ASIAN AND PACIFIC ISLANDER               Emma   
...              ...     ...                         ...                ...   
11340           2011    MALE          WHITE NON HISPANIC                LEV   
11341           2011    MALE          WHITE NON HISPANIC           AUGUSTUS   
11342           2011    MALE          WHITE NON HISPANIC              SHAUL   
11343           2011    MALE          WHITE NON HISPANIC             WESLEY   
11344           2011    MALE          WHITE NON HISPANIC            KENNETH   

       Count  Rank  
0        172     1  
1        112     2  
2        104     3  
3         99     4  
4         99     4  
...      ...   ...  
11340     10    97  
11341     10    97  
11342     10    97  
11343     10    97  
11344     10    97  

[11345 rows x 6 columns]

In [29]:
millions = pd.read_csv('data/mega_millions.csv', index_col=0)
millions

Winning Numbers  Mega Ball  Multiplier
Draw Date                                        
02/15/2019  10 38 40 43 65         12         2.0
02/12/2019  15 32 39 50 65          7         3.0
02/08/2019  14 24 31 42 48         13         3.0
02/05/2019  03 34 36 59 66          7         2.0
02/01/2019  02 37 48 66 68         11         5.0
...                    ...        ...         ...
05/31/2002  12 28 45 46 52         47         NaN
05/28/2002  06 21 22 29 32         24         NaN
05/24/2002  02 04 32 44 52         36         NaN
05/21/2002  04 28 39 41 44          9         NaN
05/17/2002  15 18 25 33 47         30         NaN

[1746 rows x 3 columns]

In [3]:
#데이터 인덱싱하기
import pandas as pd 
iphone_df = pd.read_csv('data/iphone.csv', index_col=0)
iphone_df

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [4]:
#row, column이름
iphone_df.loc['iPhone 8', '메모리']

'2GB'

In [5]:
#한 줄 전체
iphone_df.loc['iPhone 8', :]

출시일        2017-09-22
디스플레이             4.7
메모리               2GB
출시 버전        iOS 11.0
Face ID            No
Name: iPhone 8, dtype: object

In [9]:
iphone_df.loc[:,'출시일']

iPhone 7         2016-09-16
iPhone 7 Plus    2016-09-16
iPhone 8         2017-09-22
iPhone 8 Plus    2017-09-22
iPhone X         2017-11-03
iPhone XS        2018-09-21
iPhone XS Max    2018-09-21
Name: 출시일, dtype: object

In [10]:
iphone_df['출시일']

iPhone 7         2016-09-16
iPhone 7 Plus    2016-09-16
iPhone 8         2017-09-22
iPhone 8 Plus    2017-09-22
iPhone X         2017-11-03
iPhone XS        2018-09-21
iPhone XS Max    2018-09-21
Name: 출시일, dtype: object

In [18]:
iphone_df.loc[:, ['디스플레이','메모리']]

디스플레이  메모리
iPhone 7         4.7  2GB
iPhone 7 Plus    5.5  3GB
iPhone 8         4.7  2GB
iPhone 8 Plus    5.5  3GB
iPhone X         5.8  3GB
iPhone XS        5.8  4GB
iPhone XS Max    6.5  4GB

In [7]:
type(iphone_df.loc['iPhone 8']) #series 일차원

pandas.core.series.Series

In [16]:
type(iphone_df.loc[:, ['디스플레이','메모리']]) #DataFrame 이차원

pandas.core.frame.DataFrame

In [19]:
iphone_df.loc['iPhone 7':'iPhone X'] #row인덱싱

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes

In [21]:
iphone_df.loc[:,'메모리':'Face ID']#columns 인덱싱

메모리     출시 버전 Face ID
iPhone 7       2GB  iOS 10.0      No
iPhone 7 Plus  3GB  iOS 10.0      No
iPhone 8       2GB  iOS 11.0      No
iPhone 8 Plus  3GB  iOS 11.0      No
iPhone X       3GB  iOS 11.1     Yes
iPhone XS      4GB  iOS 12.0     Yes
iPhone XS Max  4GB  iOS 12.0     Yes

In [22]:
iphone_df.loc['iPhone 7':'iPhone X','출시일':'메모리']

출시일  디스플레이  메모리
iPhone 7       2016-09-16    4.7  2GB
iPhone 7 Plus  2016-09-16    5.5  3GB
iPhone 8       2017-09-22    4.7  2GB
iPhone 8 Plus  2017-09-22    5.5  3GB
iPhone X       2017-11-03    5.8  3GB

In [25]:
iphone_df.loc[[True, False, True, False,True,True,True]]

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [29]:
iphone_df.loc[:, [True, False, False, False, False]]

출시일
iPhone 7       2016-09-16
iPhone 7 Plus  2016-09-16
iPhone 8       2017-09-22
iPhone 8 Plus  2017-09-22
iPhone X       2017-11-03
iPhone XS      2018-09-21
iPhone XS Max  2018-09-21

In [31]:
iphone_df['디스플레이'] > 5

iPhone 7         False
iPhone 7 Plus     True
iPhone 8         False
iPhone 8 Plus     True
iPhone X          True
iPhone XS         True
iPhone XS Max     True
Name: 디스플레이, dtype: bool

In [32]:
iphone_df.loc[iphone_df['디스플레이'] > 5] #디스플레이가 5이상인것만 출력

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [38]:
iphone_df['Face ID'] == 'No'

iPhone 7          True
iPhone 7 Plus     True
iPhone 8          True
iPhone 8 Plus     True
iPhone X         False
iPhone XS        False
iPhone XS Max    False
Name: Face ID, dtype: bool

In [39]:
iphone_df.loc[iphone_df['Face ID'] == 'No']

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No

In [45]:
condition1 = (iphone_df['디스플레이'] > 5) & (iphone_df['Face ID'] == 'No') #and
condition2 = (iphone_df['디스플레이'] > 5) | (iphone_df['Face ID'] == 'No') #or

In [46]:
iphone_df.loc[condition1]

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No

In [48]:
iphone_df.iloc[2,4]#정수로 인덱싱하기

'No'

In [53]:
iphone_df.iloc[[1,3],[1,4]]

디스플레이 Face ID
iPhone 7 Plus    5.5      No
iPhone 8 Plus    5.5      No

In [56]:
iphone_df.iloc[1:,1:4]#연속 인덱싱

디스플레이  메모리     출시 버전
iPhone 7 Plus    5.5  3GB  iOS 10.0
iPhone 8         4.7  2GB  iOS 11.0
iPhone 8 Plus    5.5  3GB  iOS 11.0
iPhone X         5.8  3GB  iOS 11.1
iPhone XS        5.8  4GB  iOS 12.0
iPhone XS Max    6.5  4GB  iOS 12.0

In [3]:
import pandas as pd
iphone_df = pd.read_csv('data/iphone.csv', index_col=0)
iphone_df.loc['iPhone 8', '메모리']

'2GB'

In [6]:
iphone_df.loc['iPhone 8', '메모리'] = '2.5GB'#값바꾸기
iphone_df.loc['iPhone 8', '메모리']

'2.5GB'

In [9]:
iphone_df.loc['iPhone 8', '출시 버전']

'iOS 11.0'

In [11]:
iphone_df.loc['iPhone 8', '출시 버전'] = 'iOS 10.3'
iphone_df.loc['iPhone 8', '출시 버전']

'iOS 10.3'

In [12]:
iphone_df.loc['iPhone 8']#한 줄 통째로 바꾸기

출시일        2017-09-22
디스플레이             4.7
메모리             2.5GB
출시 버전        iOS 10.3
Face ID            No
Name: iPhone 8, dtype: object

In [15]:
iphone_df.loc['iPhone 8'] = ['2016-03-24', '5.8', '3.5GB', 'iOS 10.8', 'Yes']#row한 줄 통째로 바꾸기
iphone_df

출시일 디스플레이    메모리     출시 버전 Face ID
iPhone 7       2016-09-16   4.7    2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16   5.5    3GB  iOS 10.0      No
iPhone 8       2016-03-24   5.8  3.5GB  iOS 10.8     Yes
iPhone 8 Plus  2017-09-22   5.5    3GB  iOS 11.0      No
iPhone X       2017-11-03   5.8    3GB  iOS 11.1     Yes
iPhone XS      2018-09-21   5.8    4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21   6.5    4GB  iOS 12.0     Yes

In [16]:
iphone_df['디스플레이']#column한 줄 통째로 바꾸기

iPhone 7         4.7
iPhone 7 Plus    5.5
iPhone 8         5.8
iPhone 8 Plus    5.5
iPhone X         5.8
iPhone XS        5.8
iPhone XS Max    6.5
Name: 디스플레이, dtype: object

In [19]:
iphone_df['디스플레이'] = ['4.4in','5.5in','5.5in','5.8in','5.8in','5.8in','6.5in']#column한 줄 통째로 바꾸기
iphone_df

출시일  디스플레이    메모리     출시 버전 Face ID
iPhone 7       2016-09-16  4.4in    2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16  5.5in    3GB  iOS 10.0      No
iPhone 8       2016-03-24  5.5in  3.5GB  iOS 10.8     Yes
iPhone 8 Plus  2017-09-22  5.8in    3GB  iOS 11.0      No
iPhone X       2017-11-03  5.8in    3GB  iOS 11.1     Yes
iPhone XS      2018-09-21  5.8in    4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21  6.5in    4GB  iOS 12.0     Yes

In [20]:
iphone_df['Face ID'] = 'Yes'
iphone_df

출시일  디스플레이    메모리     출시 버전 Face ID
iPhone 7       2016-09-16  4.4in    2GB  iOS 10.0     Yes
iPhone 7 Plus  2016-09-16  5.5in    3GB  iOS 10.0     Yes
iPhone 8       2016-03-24  5.5in  3.5GB  iOS 10.8     Yes
iPhone 8 Plus  2017-09-22  5.8in    3GB  iOS 11.0     Yes
iPhone X       2017-11-03  5.8in    3GB  iOS 11.1     Yes
iPhone XS      2018-09-21  5.8in    4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21  6.5in    4GB  iOS 12.0     Yes

In [21]:
iphone_df[['디스플레이','Face ID']]#동시에 바꾸기

디스플레이 Face ID
iPhone 7       4.4in     Yes
iPhone 7 Plus  5.5in     Yes
iPhone 8       5.5in     Yes
iPhone 8 Plus  5.8in     Yes
iPhone X       5.8in     Yes
iPhone XS      5.8in     Yes
iPhone XS Max  6.5in     Yes

In [22]:
iphone_df[['디스플레이','Face ID']] = 'x'
iphone_df

출시일 디스플레이    메모리     출시 버전 Face ID
iPhone 7       2016-09-16     x    2GB  iOS 10.0       x
iPhone 7 Plus  2016-09-16     x    3GB  iOS 10.0       x
iPhone 8       2016-03-24     x  3.5GB  iOS 10.8       x
iPhone 8 Plus  2017-09-22     x    3GB  iOS 11.0       x
iPhone X       2017-11-03     x    3GB  iOS 11.1       x
iPhone XS      2018-09-21     x    4GB  iOS 12.0       x
iPhone XS Max  2018-09-21     x    4GB  iOS 12.0       x

In [25]:
iphone_df.loc[['iPhone 8','iPhone X']] = 'o'
iphone_df

출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16     x  2GB  iOS 10.0       x
iPhone 7 Plus  2016-09-16     x  3GB  iOS 10.0       x
iPhone 8                o     o    o         o       o
iPhone 8 Plus  2017-09-22     x  3GB  iOS 11.0       x
iPhone X                o     o    o         o       o
iPhone XS      2018-09-21     x  4GB  iOS 12.0       x
iPhone XS Max  2018-09-21     x  4GB  iOS 12.0       x

In [26]:
iphone_df.loc['iPhone 8':'iPhone XS']

출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 8                o     o    o         o       o
iPhone 8 Plus  2017-09-22     x  3GB  iOS 11.0       x
iPhone X                o     o    o         o       o
iPhone XS      2018-09-21     x  4GB  iOS 12.0       x

In [27]:
iphone_df.loc['iPhone 8':'iPhone XS'] = 'o'
iphone_df

출시일 디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16     x  2GB  iOS 10.0       x
iPhone 7 Plus  2016-09-16     x  3GB  iOS 10.0       x
iPhone 8                o     o    o         o       o
iPhone 8 Plus           o     o    o         o       o
iPhone X                o     o    o         o       o
iPhone XS               o     o    o         o       o
iPhone XS Max  2018-09-21     x  4GB  iOS 12.0       x

In [47]:
import pandas as pd 
iphone_df = pd.read_csv('data/iphone.csv', index_col=0)
iphone_df

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [48]:
iphone_df['디스플레이'] > 5

iPhone 7         False
iPhone 7 Plus     True
iPhone 8         False
iPhone 8 Plus     True
iPhone X          True
iPhone XS         True
iPhone XS Max     True
Name: 디스플레이, dtype: bool

In [49]:
iphone_df[iphone_df['디스플레이'] > 5]

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [64]:
iphone_df.iloc[[1,3],[1,4]]

디스플레이 Face ID
iPhone 7 Plus     v       v
iPhone 8 Plus     v       v

In [65]:
iphone_df.iloc[[1,3],[1,4]] = 'v'
iphone_df

출시일 디스플레이  메모리     출시 버전 Face ID    제조사
iPhone 7       2016-09-16   4.7  2GB  iOS 10.0      No  Apple
iPhone 7 Plus  2016-09-16     v  3GB  iOS 10.0       v  Apple
iPhone 8       2017-09-22   4.7  2GB  iOS 11.0      No  Apple
iPhone 8 Plus  2017-09-22     v  3GB  iOS 11.0       v  Apple
iPhone X       2017-11-03   5.8  3GB  iOS 11.1     Yes  Apple
iPhone XS      2018-09-21   5.8  4GB  iOS 12.0     Yes  Apple
iPhone XS Max  2018-09-21   6.5  4GB  iOS 12.0     Yes  Apple

In [ ]:
iphone_df.loc['iPhone XR'] = ['2018-04-03','6.1','2.4GB','iOS13.0','Yes']#추가하기

In [68]:
iphone_df

출시일 디스플레이  메모리     출시 버전 Face ID    제조사
iPhone 7       2016-09-16   4.7  2GB  iOS 10.0      No  Apple
iPhone 7 Plus  2016-09-16     v  3GB  iOS 10.0       v  Apple
iPhone 8       2017-09-22   4.7  2GB  iOS 11.0      No  Apple
iPhone 8 Plus  2017-09-22     v  3GB  iOS 11.0       v  Apple
iPhone X       2017-11-03   5.8  3GB  iOS 11.1     Yes  Apple
iPhone XS      2018-09-21   5.8  4GB  iOS 12.0     Yes  Apple
iPhone XS Max  2018-09-21   6.5  4GB  iOS 12.0     Yes  Apple

In [69]:
iphone_df['제조사'] = 'Apple'
iphone_df

출시일 디스플레이  메모리     출시 버전 Face ID    제조사
iPhone 7       2016-09-16   4.7  2GB  iOS 10.0      No  Apple
iPhone 7 Plus  2016-09-16     v  3GB  iOS 10.0       v  Apple
iPhone 8       2017-09-22   4.7  2GB  iOS 11.0      No  Apple
iPhone 8 Plus  2017-09-22     v  3GB  iOS 11.0       v  Apple
iPhone X       2017-11-03   5.8  3GB  iOS 11.1     Yes  Apple
iPhone XS      2018-09-21   5.8  4GB  iOS 12.0     Yes  Apple
iPhone XS Max  2018-09-21   6.5  4GB  iOS 12.0     Yes  Apple

In [ ]:
iphone_df.drop('iPhone XR', axis='index', inplace=True)#삭제하기(row)
iphone_df

In [71]:
iphone_df.drop('제조사', axis ='columns', inplace=True) #삭제하기(column)

In [72]:
import pandas as pd 
iphone_df = pd.read_csv('data/iphone.csv', index_col=0)
iphone_df

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7       2016-09-16    4.7  2GB  iOS 10.0      No
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8       2017-09-22    4.7  2GB  iOS 11.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone X       2017-11-03    5.8  3GB  iOS 11.1     Yes
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [73]:
iphone_df.drop(['iPhone 7','iPhone 8','iPhone X'], axis='index',inplace=True)#여러줄 삭제하기

In [74]:
iphone_df

출시일  디스플레이  메모리     출시 버전 Face ID
iPhone 7 Plus  2016-09-16    5.5  3GB  iOS 10.0      No
iPhone 8 Plus  2017-09-22    5.5  3GB  iOS 11.0      No
iPhone XS      2018-09-21    5.8  4GB  iOS 12.0     Yes
iPhone XS Max  2018-09-21    6.5  4GB  iOS 12.0     Yes

In [77]:
import pandas as pd
liverpool_df= pd.read_csv('data/liverpool.csv', index_col=0)
liverpool_df

position  born  number nationality
Roberto Firmino       FW  1991   no. 9      Brazil
Sadio Mane            FW  1992  no. 10     Senegal
Mohamed Salah         FW  1992  no. 11       Egypt
Joe Gomez             DF  1997  no. 12     England
Alisson Becker        GK  1992  no. 13      Brazil

In [81]:
liverpool_df.rename(columns={"position":"POSITION"}, inplace=True)#index,columns 설정하기
liverpool_df

POSITION  born  number nationality
Roberto Firmino       FW  1991   no. 9      Brazil
Sadio Mane            FW  1992  no. 10     Senegal
Mohamed Salah         FW  1992  no. 11       Egypt
Joe Gomez             DF  1997  no. 12     England
Alisson Becker        GK  1992  no. 13      Brazil

In [82]:
liverpool_df.rename(columns={"position":"POSITION","born":"BORN"}, inplace=True)#index,columns 설정하기
liverpool_df

POSITION  BORN  number nationality
Roberto Firmino       FW  1991   no. 9      Brazil
Sadio Mane            FW  1992  no. 10     Senegal
Mohamed Salah         FW  1992  no. 11       Egypt
Joe Gomez             DF  1997  no. 12     England
Alisson Becker        GK  1992  no. 13      Brazil

In [84]:
liverpool_df.index.name = 'Player Name' #index바꾸기
liverpool_df

POSITION  BORN  number nationality
Player Name                                       
Roberto Firmino       FW  1991   no. 9      Brazil
Sadio Mane            FW  1992  no. 10     Senegal
Mohamed Salah         FW  1992  no. 11       Egypt
Joe Gomez             DF  1997  no. 12     England
Alisson Becker        GK  1992  no. 13      Brazil

In [86]:
liverpool_df.set_index('number')#index전체바꾸기

POSITION  BORN nationality
number                           
no. 9        FW  1991      Brazil
no. 10       FW  1992     Senegal
no. 11       FW  1992       Egypt
no. 12       DF  1997     England
no. 13       GK  1992      Brazil

In [87]:
liverpool_df.index

Index(['Roberto Firmino', 'Sadio Mane', 'Mohamed Salah', 'Joe Gomez',
       'Alisson Becker'],
      dtype='object', name='Player Name')

In [90]:
liverpool_df['Player Name'] = liverpool_df.index
liverpool_df

POSITION  BORN  number nationality      Player Name
Player Name                                                        
Roberto Firmino       FW  1991   no. 9      Brazil  Roberto Firmino
Sadio Mane            FW  1992  no. 10     Senegal       Sadio Mane
Mohamed Salah         FW  1992  no. 11       Egypt    Mohamed Salah
Joe Gomez             DF  1997  no. 12     England        Joe Gomez
Alisson Becker        GK  1992  no. 13      Brazil   Alisson Becker

In [95]:
liverpool_df.set_index('number', inplace=True)

In [96]:
liverpool_df

POSITION  BORN nationality      Player Name
number                                            
no. 9        FW  1991      Brazil  Roberto Firmino
no. 10       FW  1992     Senegal       Sadio Mane
no. 11       FW  1992       Egypt    Mohamed Salah
no. 12       DF  1997     England        Joe Gomez
no. 13       GK  1992      Brazil   Alisson Becker

In [2]:
#큰 데이터 DataFrame
import pandas as pd
laptops_df = pd.read_csv('data/laptops.csv')

In [3]:
laptops_df.head(3)#위에서부터

brand             model  ram hd_type  hd_size  screen_size  price  \
0   Dell  Inspiron 15-3567    4     hdd     1024         15.6  40000   
1  Apple       MacBook Air    8     ssd      128         13.3  55499   
2  Apple       MacBook Air    8     ssd      256         13.3  71500   

  processor_brand processor_model  clock_speed graphic_card_brand  \
0           intel              i5          2.5              intel   
1           intel              i5          1.8              intel   
2           intel              i5          1.8              intel   

   graphic_card_size     os  weight comments  
0                NaN  linux    2.50      NaN  
1                2.0    mac    1.35      NaN  
2                2.0    mac    1.35      NaN

In [4]:
laptops_df.tail(6)#아래에서부터

brand           model  ram hd_type  hd_size  screen_size  price  \
161  Asus  X541UA-GO1345D    4     hdd     1024         15.6  27730   
162  Asus          A555LF    8     hdd     1024         15.6  39961   
163  Asus   X555LA-XX172D    4     hdd      500         15.6  28489   
164  Asus          X554LD    2     hdd      500         15.6  29199   
165  Asus  X550LAV-XX771D    2     hdd      500         15.6  29990   
166  Asus   X540LA-XX538T    4     hdd     1024         15.6  30899   

    processor_brand processor_model  clock_speed graphic_card_brand  \
161           intel      i3 6th gen          2.0              intel   
162           intel      i3 4th gen          1.7             nvidia   
163           intel      i3 4th gen          1.9              intel   
164           intel      i3 4th gen          1.9              intel   
165           intel      i3 4th gen          1.7              intel   
166           intel      i3 5th gen          2.0              intel   

     graphic_card_size       os  weight comments  
161                NaN    linux    1.84      NaN  
162                2.0  windows    2.30      NaN  
163                NaN    linux    2.30      NaN  
164                1.0    linux    2.30      NaN  
165                NaN    linux    2.50      NaN  
166                NaN  windows    2.30      NaN

In [5]:
laptops_df.shape #데이터 크기

(167, 15)

In [6]:
laptops_df.columns

Index(['brand', 'model', 'ram', 'hd_type', 'hd_size', 'screen_size', 'price',
       'processor_brand', 'processor_model', 'clock_speed',
       'graphic_card_brand', 'graphic_card_size', 'os', 'weight', 'comments'],
      dtype='object')

In [7]:
laptops_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 167 entries, 0 to 166
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   brand               167 non-null    object 
 1   model               167 non-null    object 
 2   ram                 167 non-null    int64  
 3   hd_type             167 non-null    object 
 4   hd_size             167 non-null    int64  
 5   screen_size         167 non-null    float64
 6   price               167 non-null    int64  
 7   processor_brand     167 non-null    object 
 8   processor_model     167 non-null    object 
 9   clock_speed         166 non-null    float64
 10  graphic_card_brand  163 non-null    object 
 11  graphic_card_size   81 non-null     float64
 12  os                  167 non-null    object 
 13  weight              160 non-null    float64
 14  comments            55 non-null     object 
dtypes: float64(4), int64(3), object(8)
memory usage: 19.7+ KB

In [8]:
laptops_df.describe()#통계값

ram     hd_size  screen_size          price  clock_speed  \
count  167.000000   167.00000   167.000000     167.000000   166.000000   
mean     6.898204   768.91018    14.775210   64132.898204     2.321084   
std      3.787479   392.99080     1.376526   42797.674010     0.554187   
min      2.000000    32.00000    10.100000   13872.000000     1.100000   
25%      4.000000   500.00000    14.000000   35457.500000     1.900000   
50%      8.000000  1024.00000    15.600000   47990.000000     2.300000   
75%      8.000000  1024.00000    15.600000   77494.500000     2.600000   
max     16.000000  2048.00000    17.600000  226000.000000     3.800000   

       graphic_card_size      weight  
count          81.000000  160.000000  
mean           52.160494    2.250812  
std           444.134142    0.648446  
min             1.000000    0.780000  
25%             2.000000    1.900000  
50%             2.000000    2.200000  
75%             4.000000    2.600000  
max          4000.000000    4.200000

In [9]:
laptops_df.sort_values(by='price')#columns(?)기준으로

brand                       model  ram hd_type  hd_size  screen_size  \
148       Acer             Aspire SW3-016     2     ssd       32         10.1   
83        Acer     A315-31CDC UN.GNTSI.001    2     ssd      500         15.6   
108       Acer  Aspire ES-15 NX.GKYSI.010     4     hdd      500         15.6   
100       Acer    A315-31-P4CRUN.GNTSI.002    4     hdd      500         15.6   
73        Acer             Aspire ES1-523     4     hdd     1024         15.6   
..         ...                         ...  ...     ...      ...          ...   
154  Microsoft      Surface Book CR9-00013    8     ssd      128         13.5   
31        Acer                 Predator 17   16     ssd      256         17.3   
96   Alienware          AW13R3-7000SLV-PUS    8     ssd      256         13.3   
90   Alienware                 15 Notebook   16     hdd     1024         15.6   
5        Apple      MacBook Pro (TouchBar)   16     ssd      512         15.0   

      price processor_brand processor_model  clock_speed graphic_card_brand  \
148   13872           intel      Atom Z8300         1.44              intel   
83    17990           intel         Celeron         1.10              intel   
108   17990             amd         A4-7210         1.80                amd   
100   18990           intel         pentium         1.10              intel   
73    19465             amd         A4-7210         1.80                amd   
..      ...             ...             ...          ...                ...   
154  178799           intel              i5         1.80              intel   
31   178912           intel              i7         2.60             nvidia   
96   190256           intel              i7         3.00             nvidia   
90   199000           intel              i7         2.60             nvidia   
5    226000           intel              i7         2.70              intel   

     graphic_card_size       os  weight  \
148                NaN  windows     1.2   
83                 NaN  windows     2.1   
108                NaN  windows     2.4   
100                NaN  windows     NaN   
73                 NaN    linux     2.4   
..                 ...      ...     ...   
154                NaN  windows     1.5   
31                 NaN  windows     4.2   
96                 6.0  windows     2.6   
90                 8.0  windows     3.5   
5                  2.0      mac     2.5   

                                              comments  
148                                                NaN  
83                                                 NaN  
108                                                NaN  
100                                                NaN  
73                                                 NaN  
..                                                 ...  
154                                                NaN  
31                                 Integrated Graphics  
96   13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...  
90      Maximum Display Resolution : 1920 x 1080 pixel  
5                                                  NaN  

[167 rows x 15 columns]

In [10]:
laptops_df.sort_values(by='price', ascending=False, inplace=True)

brand                       model  ram hd_type  hd_size  screen_size  \
5        Apple      MacBook Pro (TouchBar)   16     ssd      512         15.0   
90   Alienware                 15 Notebook   16     hdd     1024         15.6   
96   Alienware          AW13R3-7000SLV-PUS    8     ssd      256         13.3   
31        Acer                 Predator 17   16     ssd      256         17.3   
154  Microsoft      Surface Book CR9-00013    8     ssd      128         13.5   
..         ...                         ...  ...     ...      ...          ...   
73        Acer             Aspire ES1-523     4     hdd     1024         15.6   
100       Acer    A315-31-P4CRUN.GNTSI.002    4     hdd      500         15.6   
108       Acer  Aspire ES-15 NX.GKYSI.010     4     hdd      500         15.6   
83        Acer     A315-31CDC UN.GNTSI.001    2     ssd      500         15.6   
148       Acer             Aspire SW3-016     2     ssd       32         10.1   

      price processor_brand processor_model  clock_speed graphic_card_brand  \
5    226000           intel              i7         2.70              intel   
90   199000           intel              i7         2.60             nvidia   
96   190256           intel              i7         3.00             nvidia   
31   178912           intel              i7         2.60             nvidia   
154  178799           intel              i5         1.80              intel   
..      ...             ...             ...          ...                ...   
73    19465             amd         A4-7210         1.80                amd   
100   18990           intel         pentium         1.10              intel   
108   17990             amd         A4-7210         1.80                amd   
83    17990           intel         Celeron         1.10              intel   
148   13872           intel      Atom Z8300         1.44              intel   

     graphic_card_size       os  weight  \
5                  2.0      mac     2.5   
90                 8.0  windows     3.5   
96                 6.0  windows     2.6   
31                 NaN  windows     4.2   
154                NaN  windows     1.5   
..                 ...      ...     ...   
73                 NaN    linux     2.4   
100                NaN  windows     NaN   
108                NaN  windows     2.4   
83                 NaN  windows     2.1   
148                NaN  windows     1.2   

                                              comments  
5                                                  NaN  
90      Maximum Display Resolution : 1920 x 1080 pixel  
96   13.3 inch FHD (1920 x 1080) IPS Anti-Glare 300...  
31                                 Integrated Graphics  
154                                                NaN  
..                                                 ...  
73                                                 NaN  
100                                                NaN  
108                                                NaN  
83                                                 NaN  
148                                                NaN  

[167 rows x 15 columns]

In [11]:
#Series
import pandas as pd
laptops_df = pd.read_csv('data/laptops.csv')

In [12]:
laptops_df['brand']

0       Dell
1      Apple
2      Apple
3      Apple
4      Apple
       ...  
162     Asus
163     Asus
164     Asus
165     Asus
166     Asus
Name: brand, Length: 167, dtype: object

In [13]:
laptops_df['brand'].unique()#브랜드종류

array(['Dell', 'Apple', 'Acer', 'HP', 'Lenovo', 'Alienware', 'Microsoft',
       'Asus'], dtype=object)

In [14]:
laptops_df['brand'].value_counts()#몇번씩

HP           55
Acer         35
Dell         31
Lenovo       18
Asus          9
Apple         7
Microsoft     6
Alienware     6
Name: brand, dtype: int64

In [15]:
laptops_df['brand'].describe()#요약본

count     167
unique      8
top        HP
freq       55
Name: brand, dtype: object

In [17]:
#test
import pandas as pd
world_df = pd.read_csv('data/world_cities.csv', index_col=0)
world_df

City / Urban area     Country  Population  Land area (in sqKm)
0        Buenos Aires   Argentina    11200000                 2266
1           Melbourne   Australia     3162000                 2080
2              Sydney   Australia     3502000                 1687
3            Brisbane   Australia     1508000                 1603
4               Perth   Australia     1177000                  964
..                ...         ...         ...                  ...
245            Canton         USA      267000                  372
246           Spokane         USA      335000                  371
247          Tashkent  Uzbekistan     2200000                  531
248  Ho Chi Minh City     Vietnam     4900000                  518
249            Harare    Zimbabwe     1750000                  712

[249 rows x 4 columns]

In [25]:
world_df['City / Urban area'].shape #크기

(249,)

In [31]:
world_df['Density'] = world_df['Population'] / world_df['Land area (in sqKm)']
density_df = world_df[world_df['Density'] > 10000]
density_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19 entries, 32 to 129
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   City / Urban area    19 non-null     object 
 1   Country              19 non-null     object 
 2   Population           19 non-null     int64  
 3   Land area (in sqKm)  19 non-null     int64  
 4   Density              19 non-null     float64
dtypes: float64(1), int64(2), object(2)
memory usage: 912.0+ bytes


In [34]:
density_ranks = world_df.sort_values(by="Density", ascending = False)
density_ranks['City / Urban area']

75              Mumbai
74             Kolkata
101            Karachi
99               Lagos
34            Shenzhen
            ...       
195        Chattanooga
224          Asheville
57                 Pau
221            Hickory
197    Barnstable Town
Name: City / Urban area, Length: 249, dtype: object

In [37]:
import pandas as pd
import numpy as np
world_cities = pd.read_csv('data/world_cities.csv', index_col=0)
world_cities['Country']

0       Argentina
1       Australia
2       Australia
3       Australia
4       Australia
          ...    
245           USA
246           USA
247    Uzbekistan
248       Vietnam
249      Zimbabwe
Name: Country, Length: 249, dtype: object

In [40]:
countries = world_cities['Country'].value_counts()
countries

USA          105
France        15
Brazil        10
Canada         9
Germany        8
            ... 
Finland        1
Singapore      1
Greece         1
Egypt          1
Chile          1
Name: Country, Length: 61, dtype: int64

In [41]:
countries[countries == 4]

Italy    4
Name: Country, dtype: int64