<a href="https://colab.research.google.com/github/Hyuna13/Data_Science/blob/master/numpy_%ED%96%89%EB%A0%AC%EA%B3%84%EC%82%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
A = np.array([
              [1, -1, 2],
              [3,2,2],
              [4,1,2]
])

B = np.random.rand(3, 3)

In [4]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [5]:
B

array([[0.41374874, 0.77377447, 0.21241224],
       [0.6817703 , 0.96415948, 0.09795249],
       [0.89844817, 0.73668254, 0.84175099]])

In [6]:
#더하기
A + B

array([[ 1.41374874, -0.22622553,  2.21241224],
       [ 3.6817703 ,  2.96415948,  2.09795249],
       [ 4.89844817,  1.73668254,  2.84175099]])

In [7]:
#스칼라곱
5 * A

array([[ 5, -5, 10],
       [15, 10, 10],
       [20,  5, 10]])

In [8]:
#곱하기
np.dot(A,B)

array([[1.52887477, 1.28298006, 1.79796173],
       [4.40168316, 5.72300746, 2.5166437 ],
       [4.1336616 , 5.53262245, 2.63110345]])

In [9]:
#곱하기
A @ B

array([[1.52887477, 1.28298006, 1.79796173],
       [4.40168316, 5.72300746, 2.5166437 ],
       [4.1336616 , 5.53262245, 2.63110345]])

In [12]:
A @ B + (A + 2 * B)

array([[3.35637226, 1.83052901, 4.22278622],
       [8.76522376, 9.65132643, 4.71254869],
       [9.93055793, 8.00598753, 6.31460543]])