<a href="https://colab.research.google.com/github/Hyuna13/Data_Science/blob/master/numpy%ED%96%89%EB%A0%AC%EA%B3%84%EC%82%B0_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
A = np.array([
              [1,-1,2],
              [3,2,2],
              [4,1,2]
])

In [3]:
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2]])

In [4]:
#전치행렬
A.transpose()

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [5]:
#전치행렬
A.T

array([[ 1,  3,  4],
       [-1,  2,  1],
       [ 2,  2,  2]])

In [6]:
#단위행렬
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
A @ I

array([[ 1., -1.,  2.],
       [ 3.,  2.,  2.],
       [ 4.,  1.,  2.]])

In [9]:
#역행렬
A_inverse = np.linalg.pinv(A)
A_inverse @ A

array([[ 1.00000000e+00, -1.11022302e-16, -2.22044605e-16],
       [ 2.22044605e-16,  1.00000000e+00, -3.33066907e-16],
       [-8.88178420e-16, -1.11022302e-16,  1.00000000e+00]])