<a href="https://colab.research.google.com/github/Hyuna13/Data_Science/blob/master/numpy%ED%96%89%EB%A0%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
#행렬 (4x3행렬)
A = np.array([
          [1,-1,2],
          [3,2,2],
          [4,1,2],
          [5,3,6]
])
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 5,  3,  6]])

In [5]:
#행렬(3x2)
B = np.array([
              [-3,1],
              [4,5],
              [2,10]
])
B

array([[-3,  1],
       [ 4,  5],
       [ 2, 10]])

In [6]:
#랜덤행렬만들기
C = np.random.rand(3, 5) #3x5행렬 (0~1사이)
C

array([[0.14863936, 0.77580563, 0.89162197, 0.88324579, 0.21221002],
       [0.06878991, 0.04286276, 0.79485115, 0.5959981 , 0.95293072],
       [0.82720696, 0.09502215, 0.40196372, 0.77144386, 0.03222674]])

In [11]:
#모든값이 0인 행렬
D = np.zeros((2, 4))
D

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
#행렬에서 원소 받아오기
A

array([[ 1, -1,  2],
       [ 3,  2,  2],
       [ 4,  1,  2],
       [ 5,  3,  6]])

In [14]:
#1행 3열 받아오기 (0부터)
A[0][2]

2